version: "3"

services:
  app:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb
      - FLASK_APP=app.py
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - net

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - net

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - net
networks:
  net:


